### ISSUE TITLE
create non maven proxy_repositories

### ISSUE THREAD

**Issue by dzabel** [RiotGamesMinions/nexus_cli#110]
gem should be able to create proxy_repositories for other provider as maven2.
currently it seems that only maven2 is supported.

**Comment by brugidou** [comment]
You can already do that according to https://github.com/RiotGamesMinions/nexus_cli/blob/master/lib/nexus_cli/mixins/repository_actions.rb#L17 and i use this in the nexus Chef cookbook for rubygems or nuget

**Comment by dzabel** [comment]
@brugidou maybe i did it the wrong way.
My repository definition:
---
        'rubygems-mirror' => {
                'description' => 'Ruby Gems Mirror',
                'url' => 'https://rubygems.org',
                'policy' => 'MIXED',
                'provider' => 'rubygems-proxy'
        }
---

tried on OSS Sonatype Nexus 2.11.1-01 and OSS Sonatype Nexus 2.11.2-06.
Repository is created, but of type MAVEN. (screenshot attached)

![screen shot 2015-03-18 at 14 50 50](https://cloud.githubusercontent.com/assets/972592/6710048/4f1324c4-cd7e-11e4-9915-07ec1a15f30f.png)

Any idea? What nexus version did you use?

**Comment by dzabel** [comment]
Found my mistake. 

repository definition has to be:
---
        'rubygems-mirror' => {
                'description' => 'Ruby Gems Mirror',
                'url' => 'https://rubygems.org',
                'policy' => 'MIXED',
                'repo_provider' => 'rubygems-proxy'
        }
---
