### ISSUE TITLE
Release master branch to rubygems

### ISSUE THREAD

**Issue by brugidou** [RiotGamesMinions/nexus_cli#111]
Hi, master branch has not been released since October 2013, could we please release it to rubygems.org?

**Comment by jmauro** [comment]
+1

**Comment by Annih** [comment]
@KAllan357 are you still in charge of this gem? Would it be possible to release the master branch? 

Thanks in advance for any answer =]

**Comment by vmcdev** [comment]
@KAllan357 before pushing this we need to get the pulls approved and merged....can we please get that done too.?

**Comment by brugidou** [comment]
I would first do a release (it is very quick) and do a second release after that with the pull requests.

**Comment by Annih** [comment]
@pyro2927 or @ivey  or @reset Would it be possible to release the master branch?

**Comment by pyro2927** [comment]
@Annih, thanks for your persistence.  [4.1.1 has been pushed to RubyGems](https://rubygems.org/gems/nexus_cli/versions/4.1.1).

**Comment by Annih** [comment]
Thanks @pyro2927!

By any chance are you contributor on https://github.com/RiotGamesCookbooks/artifact-cookbook ?

**Comment by pyro2927** [comment]
@Annih I am not.
